parameters:
    default_trusted_proxies: 127.0.0.1

# see https://symfony.com/doc/current/reference/configuration/framework.html
framework:
    secret: '%env(APP_SECRET)%'
    csrf_protection: true
    trusted_proxies: '%env(default:default_trusted_proxies:TRUSTED_PROXIES)%'
    trusted_headers:
        - 'x-forwarded-for'
        - 'x-forwarded-host'
        - 'x-forwarded-proto'
        - 'x-forwarded-port'
        - 'x-forwarded-prefix'

    # Enables session support. Note that the session will ONLY be started if you read or write from it.
    # Remove or comment this section to explicitly disable session support.
    session: true

    #esi: true
    #fragments: true
    php_errors:
        log: true

    esi: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
